name: retrain_weekly
on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: pip install -r requirements.txt
      - name: Run retrain weekly
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python -m jobs.retrain_weekly
